name: permis
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_tts: ^3.0.0
  font_awesome_flutter: ^8.10.0
  flutter_svg: ^0.19.1
  animated_bottom_navigation_bar: ^0.1.2+2
  icon_picker: ^1.1.0
  line_icons: ^0.2.0
  frino_icons: ^1.0.1+4
  sleek_circular_slider: ^1.2.0+web
  liquid_progress_indicator: ^0.3.2
  image_picker: ^0.6.4
  rflutter_alert: ^1.1.0
  sp_util: ^2.0.3
  shared_preferences: ^2.0.5
  provider: ^4.3.2+3
  auto_animated: any
  step_progress_indicator: ^0.2.5+8
  flutter_intro: ^1.0.0
  toast: ^0.1.5
  tutorial_coach_mark: ^1.0.0
  fast_immutable_collections: ^4.0.6














dev_dependencies:
  hive_generator: ^0.8.1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
   - assets/iconTheme/
   - assets/imageDefinition/
   - assets/imageDefinition/explication1/
   - assets/imageDefinition/explication2/
   - assets/imageDefinition/explication3/
   - assets/profil/
   - assets/imageConducteurPassager/
   - assets/imageConducteurPassager/explication1/
   - assets/emoji/
   - assets/ImageInjonction/
   - assets/ImageSignaux/

  fonts:
    - family: reglages
      fonts:
        - asset: assets/fonts/reglages.ttf
    - family: themes
      fonts:
        - asset: assets/fonts/themes.ttf
    - family: cours
      fonts:
        - asset: assets/fonts/cours.ttf
    - family: chrono
      fonts:
        - asset: assets/fonts/chrono.ttf
    - family: jeux
      fonts:
        - asset: assets/fonts/jeux.ttf

